version: "3.9"

services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:8.9.0
    volumes:
      - /srv/var/cardano/state-preview:/data
    environment:
      - CARDANO_CONFIG=/data/config.json
      - CARDANO_TOPOLOGY=/data/topology.json
      - CARDANO_DATABASE_PATH=/data/db
      - CARDANO_SOCKET_PATH=/data/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/data/node.socket # used by cardano-cli
      - CARDANO_LOG_DIR=/data/logs
    command:
      [ "run" ]
    restart: always

  hydra-explorer:
    image: ghcr.io/input-output-hk/hydra-explorer:unstable
    volumes:
    - /srv/var/cardano/state-preview:/data
    ports:
      - "80:8080"
    command:
      [ "--node-socket", "/data/node.socket"
      , "--testnet-magic", "2"
      , "--api-port", "8080"
      # NOTE: Block in which current master scripts were published
      , "--start-chain-from", "51263.1f34e4ee2404a5e4fc8ef970b7b8717af34c1a5a22107b82cde79c5d11da93b9"
      ]
    restart: always
